spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: nidhibajaj
    password: nidhibajaj
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    schemas: public
    locations: classpath:db/migration

server:
  port: 8080
