spring:
datasource:
url: jdbc:postgresql://localhost:5432/postgres
username: nidhibajaj
password: postgres
hikari:
schema: public
jpa:
hibernate:
ddl-auto: none
flyway:
schemas: public
locations: classpath:db/migration


